### ISSUE TITLE
[Documents] How to use udao-spark and deployment on spark + K8S

### ISSUE THREAD

**Issue by shadowinlife** [Angryrou/udao-spark-optimizer#94]
I'm learning your amazing project about runtime configuration optimizer.

Is there any documents about 

1. How to deploy on spark + k8s
2. How to generated training data ( Assets in playground directory?)

If I want to handle Container OOM (spark.executor.memoryOverhead) with this framework. Is there any documents about how to add a new configuration to model?

**Comment by Angryrou** [comment]
Thanks for your interest.

1. We currently do not have a document for deployment on Spark + K8S. We do not use docker and K8s. 
2. [Here](https://github.com/udao-moo/udao-spark-optimizer?tab=readme-ov-file#preparation) might be a good start to understand how to generate training data.
3. To add `spark.executor.memoryOverhead` in the model, you can update `playground/assets/spark_configuration_aqe_on.json`, and later on update the scope of [THETA_C](https://github.com/Angryrou/udao-spark-optimizer/blob/aeff7c1715c66ab48a519caf594c54f64abc10c5/udao_trace/parser/spark_parser.py#L14)
